name: dapseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>3.12
  - macs3
  - bowtie2
  - samtools
  - deeptools
  - meme
  - fastqc
  - multiqc
  - snakemake=9.16.3
  - bbtools
  - homer
  - bedtools
  - biopython
  - pandas
