name: dapseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>3.12
  - macs3
  - bwa
  - bowtie2
  - minimap2
  - samtools
  - deeptools
  - meme
  - fastqc
  - multiqc
  - snakemake=9.16.3
  - trimmomatic
  - bedtools
  - biopython
  - pandas
  - matplotlib
